### ISSUE TITLE
JS console error when using Elementor

### ISSUE THREAD

**Issue by AdrianLuk** [tekapo/show-current-template#7] opened 2021-04-06 22:14 UTC
Plugin throws a console error when using Elementor due to absence of an element with id 'included-files-list'.

Fixed by adding an if check to `assets/js/replace.js` on line 3 like so:
```
if (document.getElementById('included-files-list')) {
    document.getElementById('included-files-list').innerHTML = c;
  }
```

**Comment by tekapo** [comment] 2021-04-29 12:34
Thank you for reporting the issue!

Could you try the new version, 0.4.6?

I've tried the new version 0.4.6 with Elementor (not pro version), I have no JS error.
So, If you still have the same issue, please let me know how to reproduce the issue step by step.

**Comment by tekapo** [comment] 2023-08-26 01:27
Since no reply for long time, close this issue.

**Closed by tekapo** 2023-08-26 01:27 UTC
